# Generated by Django 4.1.3 on 2022-11-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_date_day_month_year_record_habit_date_h_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='measurement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
