# Generated by Django 4.1.3 on 2022-11-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_habit_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='h_record',
        ),
    ]
