# Generated by Django 4.1.3 on 2022-11-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_remove_date_h_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='record',
            new_name='h_record',
        ),
        migrations.AddField(
            model_name='record',
            name='r_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit'),
        ),
    ]
