# Generated by Django 4.1.3 on 2022-11-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_alter_record_r_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='h_record',
        ),
    ]
