# Generated by Django 4.1.3 on 2022-11-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0008_alter_record_r_habit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('h_date', 'r_habit'), name='habit_per_date'),
        ),
    ]
