# Generated by Django 4.1.3 on 2022-11-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0009_record_habit_per_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='h_day',
        ),
        migrations.RemoveField(
            model_name='date',
            name='h_month',
        ),
        migrations.RemoveField(
            model_name='date',
            name='h_year',
        ),
        migrations.AddField(
            model_name='date',
            name='dday',
            field=models.IntegerField(blank=b'I01\n', null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='dmonth',
            field=models.IntegerField(blank=b'I01\n', null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='dyear',
            field=models.IntegerField(blank=b'I01\n', null=True),
        ),
    ]
