# Generated by Django 4.1.3 on 2022-11-02 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0010_remove_date_h_day_remove_date_h_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='dday',
        ),
        migrations.RemoveField(
            model_name='date',
            name='dmonth',
        ),
        migrations.RemoveField(
            model_name='date',
            name='dyear',
        ),
        migrations.AddField(
            model_name='date',
            name='h_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='habit.day'),
        ),
        migrations.AddField(
            model_name='date',
            name='h_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='habit.month'),
        ),
        migrations.AddField(
            model_name='date',
            name='h_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='habit.year'),
        ),
    ]
