# Generated by Django 4.1.3 on 2022-11-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0012_remove_record_habit_per_date_alter_record_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='target',
            field=models.FloatField(default=0),
        ),
    ]
