# Generated by Django 4.1.3 on 2022-11-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0014_habit_actual_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='date',
            constraint=models.UniqueConstraint(fields=('h_year', 'h_month', 'h_day'), name='one_date'),
        ),
    ]
