# Generated by Django 4.1.3 on 2022-11-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0015_date_one_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='h_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='habit.day'),
        ),
        migrations.AlterField(
            model_name='date',
            name='h_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='habit.month'),
        ),
        migrations.AlterField(
            model_name='date',
            name='h_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='habit.year'),
        ),
    ]
